server:
  port: 3344

spring:
  application:
    name:  microservicecloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kocoolcool/microservicecloud-config.git #GitHub上面的git仓库名字
#http://config-3344.com:3344/master/aplicaton-dev.yml
#http://config-3344.com:3344/aplicaton-dev/dev/master
#http://config-3344.com:3344/aplicaton-dev.yml

